### ISSUE TITLE
'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by jzxww** [VisionLearningGroup/R-C3D#16]
when i run the script of "script_train.sh":
I got a AttributeError: 'NoneType' object has no attribute 'astype'
the whole like this:
```
I0328 11:24:09.393389 27646 net.cpp:761] Ignoring source layer loss
Solving...
Traceback (most recent call last):
  File "./experiments/thumos14/train_net.py", line 97, in <module>
    max_iters=args.max_iters)
  File "/****/R-C3D/experiments/thumos14/../../lib/tdcnn/train.py", line 159, in train_net
    model_paths = sw.train_model(max_iters)
  File "/****/R-C3D/experiments/thumos14/../../lib/tdcnn/train.py", line 100, in train_model
    self.solver.step(1)
  File "/****/Deeplearning/R-C3D/experiments/thumos14/../../lib/roi_data_layer/layer.py", line 124, in forward
    blobs = self._get_next_minibatch()
  File "/****/R-C3D/experiments/thumos14/../../lib/roi_data_layer/layer.py", line 48, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/****/R-C3D/experiments/thumos14/../../lib/roi_data_layer/minibatch.py", line 31, in get_minibatch
    video_blob = _get_video_blob(roidb, random_scale_inds)
  File "/****/R-C3D/experiments/thumos14/../../lib/roi_data_layer/minibatch.py", line 72, in _get_video_blob
    cfg.TRAIN.CROP_SIZE, random_idx)
  File "/****/R-C3D/experiments/thumos14/../../lib/utils/blob.py", line 32, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'
```
Does someone else have this problem? please help,thanks a lot

**Comment by zzw1123** [comment]
@jzxww @JKANG94 Have you two solved the problem? Could you please tell me the solution?
Thanks a lot!
