### ISSUE TITLE
python generate_roidb_validation.py

### ISSUE THREAD

**Issue by LiliMeng** [VisionLearningGroup/R-C3D#4]
Thanks a lot for sharing the code.
It works well for generate_roidb_train.py, but when generating the validation using
$python generate_roidb_validation.py

It has the following errors: 
Generate Classes
0
1
2
../.././preprocess/activityNet/frames/validation/tTEAlDsmZrA/image_-0001.jpg
Traceback (most recent call last):
  File "generate_roidb_validation.py", line 82, in <module>
    val_roidb = generate_roidb('validation')
  File "generate_roidb_validation.py", line 57, in generate_roidb
    tmp = generate_roi(vid, start, end, stride, split)
  File "generate_roidb_validation.py", line 37, in generate_roi
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Any suggestions?
Thanks again!

**Comment by huijuan88** [comment]
../.././preprocess/activityNet/frames/validation/tTEAlDsmZrA/image_-0001.jpg

This image frame name is wrong.


On Dec 17, 2017, at 15:11, LiliMeng <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot for sharing the code.
It works well for generate_roidb_train.py, but when generating the validation using
$python generate_roidb_validation.py

It has the following errors:
Generate Classes
0
1
2
../.././preprocess/activityNet/frames/validation/tTEAlDsmZrA/image_-0001.jpg
Traceback (most recent call last):
File "generate_roidb_validation.py", line 82, in
val_roidb = generate_roidb('validation')
File "generate_roidb_validation.py", line 57, in generate_roidb
tmp = generate_roi(vid, start, end, stride, split)
File "generate_roidb_validation.py", line 37, in generate_roi
raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Any suggestions?
Thanks again!
